title: 예제 기술 블로그
email: exmaple@example.com
description: |
  Connect Everything 새로운 연결, 새로운 세상.
  연결의 혁신으로 세상은 더욱 가깝고 새로워진다고 예제는 믿습니다.
baseurl: ''
url: 'http://example.com'
timezone: Asia/Seoul 

repository: berryzed/techlog

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/techlog/page/:num/'

collections:
  authors:
    output: true
    permalink: /techlog/authors/:path/
  tags:
    output: true
    permalink: /techlog/tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: example@example.com
image: '/techlog/assets/images/default_blog_cover.jpg'
asset_url: /techlog/assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
# google_analytics:
#   ua: 'UA-72007721-1'
# facebook:
#   app_id: '1204347326263800'
#   username: kakaocorp
# twitter:
#   username: kakaodev
# google_plus:
#   username: kakaodev
github:
  username: berryzed
